apiVersion: apps/v1
kind: Deployment
metadata:
  name: niq-api
  namespace: junior-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: niq-api
  template:
    metadata:
      labels:
        app: niq-api
    spec:
      containers:
      - name: niq-api
        image: niq-api:1.0
        ports:
        - containerPort: 8080
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: DB_PORT
